version: '3.7'
services:
  frontend:
    image: node:latest
    ports:
      - "8002:3000"
    container_name: alten-technical-test
    tty: true
    volumes:
      - .:/home/www/alten-technical-test/
    working_dir: /home/www/alten-technical-test/
    networks:
      static-network-alten-technical-test:
        ipv4_address: 172.26.128.1

networks:
  static-network-alten-technical-test:
    ipam:
      config:
        - subnet: 172.26.0.0/16
